export const FETCH_LATEST_STATISTICS = 'FETCH_LATEST_STATISTICS';
export const FETCH_LATEST_STATISTICS_SUCCESS = 'FETCH_LATEST_STATISTICS_SUCCESS';
export const FETCH_LATEST_STATISTICS_FAILURE = 'FETCH_LATEST_STATISTICS_FAILURE';

